export const SIGN_IN_USER = "SIGN_IN_USER";
export const SIGN_IN_ADMIN = "SIGN_IN_ADMIN";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const GET_ALL_USER = "GET_ALL_USER";
export const DELETE_USER = "DELETE_USER";
export const ADD_USER = "ADD_USER";
export const GET_DETAIL_USER = "GET_DETAIL_USER";
export const UPDATE_USER = "UPDATE_USER";
export const FORGOT_PASSWORD_USER = "FORGOT_PASSWORD_USER";
export const RESET_PASSWORD_USER = "RESET_PASSWORD_USER";
export const GET_INFORMATION_USER = "GET_INFORMATION_USER";
export const GET_CATEGORY = "GET_CATEGORY";
export const GET_DETAIL_CATEGORY = "GET_DETAIL_CATEGORY";
export const GET_CATEGORY_POST = "GET_CATEGORY_POST";
export const GET_DETAIL_CATEGORY_POST = "GET_DETAIL_CATEGORY_POST";
export const GET_USER_POST = "GET_USER_POST";
export const ADD_USER_POST = "ADD_USER_POST";
export const DELETE_USER_POST = "DELETE_USER_POST";
export const EDIT_PROFILE_USER = "EDIT_PROFILE_USER";
export const GET_COMMENT_POST = "GET_COMMENT_POST";
export const GET_USER_COMMENT_POST = "GET_USER_COMMENT_POST";
export const USER_CREATE_COMMENT_POST = "USER_CREATE_COMMENT_POST";
export const USER_PROFILE_COMMENT = "USER_PROFILE_COMMENT";
export const USER_CREATE_COMMENT_HIGHTLIGHT = "USER_CREATE_COMMENT_HIGHTLIGHT";
// -------MANAGE_GET_POST
export const MANAGE_GET_POST = "MANAGE_GET_POST";

// MANAGE_GET_CATEGORIES
export const MANAGE_GET_CATEGORIES = "MANAGE_GET_CATEGORIES";
