version: "3"

services:
  
  post-service:
    build:
      dockerfile: Dockerfile
      context: ./post-service
    container_name: post-service
    ports:
      - "8002:8002"
    restart: always
    volumes:
      - .:/server
      - /server/post-service/node_modules

  comment-service:
    build:
      dockerfile: Dockerfile
      context: ./comment-service
    container_name: comment-service
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "nosql-db"
    volumes:
      - .:/server
      - /server/comment-service/node_modules

  user-service:
    build:
      dockerfile: Dockerfile
      context: ./user-service
    container_name: user-service
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - .:/server
      - /server/user-service/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - post-service 
      - user-service
    ports:
      - "80:80"
