
POST http://localhost:3000/api/user/register
Content-Type: application/json
{
    "email": "minhtuetql@gmail.com",
    "password": "12345"
}
###
POST http://localhost:3000/api/user/forgot-password
Content-Type: application/json

{
    "email": "minhtuetql@gmail.com"
}

# ###
GET http://localhost:3000/api/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MWFkY2E3YThmYTMxMmM4MTdiOGQ1ZTEiLCJpYXQiOjE2Mzg3Nzk1MTR9.Zbi9hmpzrk4sFbAALSu0d956bpEwZRLYgFOx0HTbQA4
Content-Type: application/json

###
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "thomas@gmail.com",
    "password": "thomas"
}

# ###



